export const environment = {
  production: true,
  BASE_URL:'https://aliklima.vercel.app',
  COOKIE_VALUE:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJEQzIxZUROa0pubVpTTTRJSlcwcTRaYnYiLCJpYXQiOjE3MTQ5MzAzNjAsImF1ZCI6ImFzYmFqcmFtLTlhbDJ0eW5qcS1iYXJpMTIzcy1wcm9qZWN0cy52ZXJjZWwuYXBwIiwidXNlcm5hbWUiOiJiYXJpMTIzIiwic3ViIjoic3NvLXByb3RlY3Rpb24ifQ.g-fVd5gOKJ38gWpVuQidIQUwxqMJlBaaqN_9H7YqqPM'
};
